const APARTMENTS = [
  {
    "apartment": "Stanford Villa",
    "city": "Palo Alto",
    "address": "3351-3375 Alma St, Palo Alto, CA 94306",
    "latitude": 37.4201642,
    "longitude": -122.1261222,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,000-1,050",
    "listedRent": "$3,650-$4,170",
    "priceBasis": "Base rent",
    "floorplanUnit": "Sequoia (Units 106 now, 140 Apr 1); Ponderosa (multiple units now)",
    "specials": null,
    "deposit": "$800",
    "leaseTerms": null,
    "review": "3.9 (5 reviews)",
    "officialWebsite": "https://www.stanfordvilla.com",
    "listingSource": "https://www.apartments.com/stanford-villa-palo-alto-ca/5ezwzbq/",
    "closestCaltrain": "California Ave",
    "distance": "not yet verified",
    "walkTime": "not yet verified",
    "notes": "Two 2B/2B floorplans were live: Sequoia 1,000 sq ft and Ponderosa 1,050 sq ft.",
    "researchDate": "2026-03-17",
    "primarySource": "Apartments.com live floor plan page"
  },
  {
    "apartment": "Montage Apartments",
    "city": "Palo Alto",
    "address": "4020 El Camino Real, Palo Alto, CA 94306",
    "latitude": 37.4152258,
    "longitude": -122.1282764,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,000",
    "listedRent": "$4,995",
    "priceBasis": "Base rent",
    "floorplanUnit": "NEWLY REMODELED Upstairs 2BRx2BA",
    "specials": "One month free with a 15-month lease and immediate move-in",
    "deposit": "$1,000",
    "leaseTerms": "15 months for special",
    "review": "4.0 (0 reviews)",
    "officialWebsite": null,
    "listingSource": "https://www.apartments.com/montage-apartments-palo-alto-ca/fqckbxs/",
    "closestCaltrain": "California Ave",
    "distance": "not yet verified",
    "walkTime": "not yet verified",
    "notes": "Single 2B/2B floorplan listed as available now.",
    "researchDate": "2026-03-17",
    "primarySource": "Apartments.com live floor plan page"
  },
  {
    "apartment": "Southwood Apartments",
    "city": "Palo Alto",
    "address": "2850 Middlefield Rd, Palo Alto, CA 94306",
    "latitude": 37.4320555,
    "longitude": -122.1273465,
    "earliestAvailability": "2026-04-10",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "980",
    "listedRent": "$4,195",
    "priceBasis": "Base rent",
    "floorplanUnit": "2x2A / Unit 113",
    "specials": null,
    "deposit": "$1,000",
    "leaseTerms": null,
    "review": "3.9 (1 review)",
    "officialWebsite": "https://www.southwood-apartments.com",
    "listingSource": "https://www.apartments.com/southwood-apartments-palo-alto-ca/6f8zpmt/",
    "closestCaltrain": "California Ave",
    "distance": "1.6 mi",
    "walkTime": "not shown",
    "notes": "Only one 2B/2B unit was live and it becomes available on April 10, 2026.",
    "researchDate": "2026-03-17",
    "primarySource": "Apartments.com live floor plan page"
  },
  {
    "apartment": "345 Sheridan Ave Unit SI FL3-ID806",
    "city": "Palo Alto",
    "address": "345 Sheridan Ave, Palo Alto, CA 94306",
    "latitude": 37.4250735,
    "longitude": -122.1407098,
    "earliestAvailability": "2026-03-18",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,097",
    "listedRent": "$4,090 lowest advertised; $4,400 for 1-year stay",
    "priceBasis": "Term-dependent furnished rate",
    "floorplanUnit": "Blueground unit SI FL3-ID806",
    "specials": null,
    "deposit": null,
    "leaseTerms": "1-12 months",
    "review": "n/a on unit listing",
    "officialWebsite": "https://www.theblueground.com",
    "listingSource": "https://www.apartments.com/345-sheridan-ave-palo-alto-ca-unit-si-fl3-id806/rhckc00/",
    "closestCaltrain": "California Ave",
    "distance": "not yet verified",
    "walkTime": "not yet verified",
    "notes": "Furnished Blueground unit. Lowest rate depends on stay length; 1-year pricing was explicitly listed at $4,400/month.",
    "researchDate": "2026-03-17",
    "primarySource": "Apartments.com unit page"
  },
  {
    "apartment": "Sevens",
    "city": "Mountain View",
    "address": "777 W Middlefield Rd, Mountain View, CA 94043",
    "latitude": 37.4027987,
    "longitude": -122.076013,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,021-1,240+",
    "listedRent": "$5,979-$7,184",
    "priceBasis": "Total monthly price",
    "floorplanUnit": "B4 (Units B-130 now, B-276 now, B-176 Mar 31, B-145 Mar 31); additional 2B/2B floorplans also listed",
    "specials": "Up to 8 weeks free base rent",
    "deposit": null,
    "leaseTerms": "Minimum lease term applies",
    "review": "5.0 (2 reviews)",
    "officialWebsite": null,
    "listingSource": "https://www.apartments.com/sevens-mountain-view-ca/3rr7vmg/",
    "closestCaltrain": "Mountain View",
    "distance": "1.3 mi",
    "walkTime": "not yet verified (4 min drive)",
    "notes": "At least one 2B/2B floorplan was available now and another set by Mar 31. Apartments.com labels pricing as total monthly price.",
    "researchDate": "2026-03-17",
    "primarySource": "Apartments.com live floor plan page"
  },
  {
    "apartment": "Rowe at Pear Village",
    "city": "Mountain View",
    "address": "1265 Pear Ave, Mountain View, CA 94043",
    "latitude": 37.4142233,
    "longitude": -122.0741342,
    "earliestAvailability": "2026-03-22",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,146-1,318",
    "listedRent": "$5,190-$5,650",
    "priceBasis": "Total monthly price",
    "floorplanUnit": "Unit 260 (1,146 sq ft, Mar 22); 2A.2 / Unit 332 (1,318 sq ft, Mar 25)",
    "specials": null,
    "deposit": null,
    "leaseTerms": null,
    "review": "4.9 (11 reviews)",
    "officialWebsite": null,
    "listingSource": "https://www.apartments.com/rowe-at-pear-village-mountain-view-ca/7fyfd6x/",
    "closestCaltrain": "Mountain View",
    "distance": "2.1 mi",
    "walkTime": "not yet verified",
    "notes": "A May 7 unit was excluded from the eligible interpretation because it misses the early-April cutoff.",
    "researchDate": "2026-03-17",
    "primarySource": "Apartments.com live floor plan page"
  },
  {
    "apartment": "Landsby",
    "city": "Mountain View",
    "address": "2580-2590 California St, Mountain View, CA 94040",
    "latitude": 37.4052864,
    "longitude": -122.109234,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "964-1,047",
    "listedRent": "$5,618-$5,710",
    "priceBasis": "Total monthly price",
    "floorplanUnit": "2A-6 / Unit 1511 now; 2K-1 / Unit 3521 Mar 21; 2B-1 / Unit 3319 Mar 23",
    "specials": null,
    "deposit": null,
    "leaseTerms": null,
    "review": "4.6 (57 reviews)",
    "officialWebsite": null,
    "listingSource": "https://www.apartments.com/landsby-mountain-view-ca/8mzlqg0/",
    "closestCaltrain": "San Antonio",
    "distance": "0.2 mi",
    "walkTime": "4 min",
    "notes": "A second 2B-1 unit for May 8 was excluded from the eligible interpretation.",
    "researchDate": "2026-03-17",
    "primarySource": "Apartments.com live floor plan page"
  },
  {
    "apartment": "Verve",
    "city": "Mountain View",
    "address": "2020 W El Camino Real, Mountain View, CA 94040",
    "latitude": 37.3947662,
    "longitude": -122.1000645,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,121-1,651",
    "listedRent": "$5,139-$5,736",
    "priceBasis": "Base rent",
    "floorplanUnit": "B2A / Unit 322 now; B2G / Unit 410 Mar 27",
    "specials": null,
    "deposit": null,
    "leaseTerms": null,
    "review": "4.0 (0 reviews)",
    "officialWebsite": "https://www.udr.com",
    "listingSource": "https://www.apartments.com/verve-mountain-view-ca/dfw92yk/",
    "closestCaltrain": "San Antonio",
    "distance": "1.2 mi",
    "walkTime": "not yet verified",
    "notes": "Another 2B/2B unit (B2J / Unit 412) was listed for Apr 23 and excluded from the eligible interpretation.",
    "researchDate": "2026-03-17",
    "primarySource": "Apartments.com live floor plan page"
  },
  {
    "apartment": "The Shadows Apartments",
    "city": "Mountain View",
    "address": "750 N Shoreline Blvd, Mountain View, CA 94043",
    "latitude": 37.4050688,
    "longitude": -122.0782316,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,025",
    "listedRent": "$4,595",
    "priceBasis": "Base rent",
    "floorplanUnit": "E floorplan",
    "specials": "$1,000 off when you look and lease; water, sewer, and garbage included in rent",
    "deposit": "$800",
    "leaseTerms": null,
    "review": "4.0 (0 reviews)",
    "officialWebsite": null,
    "listingSource": "https://www.apartments.com/the-shadows-apartments-mountain-view-ca/ysm3jjr/",
    "closestCaltrain": "Mountain View",
    "distance": "1.3 mi",
    "walkTime": "not yet verified",
    "notes": "The 2B/2B floorplan was listed as available now without individual unit rows on Apartments.com.",
    "researchDate": "2026-03-17",
    "primarySource": "Apartments.com live floor plan page"
  },
  {
    "apartment": "MV Apartments",
    "city": "Mountain View",
    "address": "2700 W El Camino Real, Mountain View, CA 94040",
    "latitude": 37.3857514,
    "longitude": -122.0841169,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,013",
    "listedRent": "$5,549",
    "priceBasis": "Base rent",
    "floorplanUnit": "Chestnut / Unit 528 now",
    "specials": null,
    "deposit": null,
    "leaseTerms": null,
    "review": "4.8 (13 reviews)",
    "officialWebsite": null,
    "listingSource": "https://www.apartments.com/mv-apartments-mountain-view-ca/tlm9sdb/",
    "closestCaltrain": "San Antonio",
    "distance": "0.7 mi",
    "walkTime": "14 min",
    "notes": "A second Chestnut unit for Apr 14 was excluded from the eligible interpretation because it is after the cutoff.",
    "researchDate": "2026-03-17",
    "primarySource": "Apartments.com live floor plan page"
  },
  {
    "apartment": "Maplewood Apartments",
    "city": "Mountain View",
    "address": "1885 California St, Mountain View, CA 94041",
    "latitude": 37.3964905,
    "longitude": -122.0938499,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "947",
    "listedRent": "$3,700-$3,800",
    "priceBasis": "Base rent",
    "floorplanUnit": "Plan B1 / Unit 29 now; Unit 31 Apr 7",
    "specials": "Up to 1 month on us",
    "deposit": "$600",
    "leaseTerms": null,
    "review": "4.0 (0 reviews)",
    "officialWebsite": null,
    "listingSource": "https://www.apartments.com/maplewood-apartments-mountain-view-ca/0h511d1/",
    "closestCaltrain": "San Antonio",
    "distance": "1.3 mi",
    "walkTime": "not yet verified",
    "notes": "Two 2B/2B units were live and both meet the early-April cutoff.",
    "researchDate": "2026-03-17",
    "primarySource": "Apartments.com live floor plan page"
  },
  {
    "apartment": "Hartwood",
    "city": "Sunnyvale",
    "address": "401 Willow Ave, Sunnyvale, CA 94086",
    "latitude": 37.3699627,
    "longitude": -121.9976623,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,223",
    "listedRent": "$5,200-$5,515",
    "priceBasis": "Base rent",
    "floorplanUnit": "2 Bed/2 Bath-B5 / Unit 2109 now; Unit 2402 Apr 5; Unit 1307 Apr 7",
    "specials": "Exceptional leasing specials available for a limited time",
    "deposit": null,
    "leaseTerms": null,
    "review": "4.0 (0 reviews)",
    "officialWebsite": null,
    "listingSource": "https://www.apartments.com/hartwood-sunnyvale-ca/nzqhytq/",
    "closestCaltrain": "Lawrence",
    "distance": "0.1 mi",
    "walkTime": "1 min",
    "notes": "Other 2B/2B floorplans were listed but marked not available; B5 is the live qualifying option.",
    "researchDate": "2026-03-17",
    "primarySource": "Apartments.com live floor plan page"
  },
  {
    "apartment": "Savoy",
    "city": "Sunnyvale",
    "address": "1120 Kifer Rd, Sunnyvale, CA 94086",
    "latitude": 37.3732914,
    "longitude": -121.9998913,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,228-1,344",
    "listedRent": "$4,946-$5,108",
    "priceBasis": "Total monthly price",
    "floorplanUnit": "B5.4 / Unit 1-415 now; B5 / Unit 2-550 Mar 24; B7 / Unit 2-321 Apr 8",
    "specials": null,
    "deposit": "$600",
    "leaseTerms": null,
    "review": "4.4 (98 reviews)",
    "officialWebsite": null,
    "listingSource": "https://www.apartments.com/savoy-sunnyvale-ca/wz9c7ck/",
    "closestCaltrain": "Lawrence",
    "distance": "0.6 mi",
    "walkTime": "12 min",
    "notes": "A B5 unit for Apr 23 and a B2 unit for Apr 29 were excluded from the eligible interpretation.",
    "researchDate": "2026-03-17",
    "primarySource": "Apartments.com live floor plan page"
  },
  {
    "apartment": "Encasa",
    "city": "Sunnyvale",
    "address": "550 E Weddell Dr, Sunnyvale, CA 94089",
    "latitude": 37.3988598,
    "longitude": -122.0142129,
    "earliestAvailability": "2026-03-24",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,175",
    "listedRent": "$4,855",
    "priceBasis": "Total monthly price",
    "floorplanUnit": "2x2e / Unit 7423",
    "specials": null,
    "deposit": null,
    "leaseTerms": null,
    "review": "4.2 (24 reviews)",
    "officialWebsite": null,
    "listingSource": "https://www.apartments.com/encasa-sunnyvale-ca/s1ktnb6/",
    "closestCaltrain": "Lawrence",
    "distance": "3.0 mi",
    "walkTime": "not yet verified",
    "notes": "Only one live 2B/2B unit met the cutoff; the rest of the 2B/2B plans were not available.",
    "researchDate": "2026-03-17",
    "primarySource": "Apartments.com live floor plan page"
  },
  {
    "apartment": "Naya",
    "city": "Sunnyvale",
    "address": "1095 W El Camino Real, Sunnyvale, CA 94087",
    "latitude": 37.3734276,
    "longitude": -122.0512255,
    "earliestAvailability": "2026-03-19",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,013",
    "listedRent": "$4,789",
    "priceBasis": "Total monthly price",
    "floorplanUnit": "Floor Plan C / Unit 303",
    "specials": null,
    "deposit": null,
    "leaseTerms": null,
    "review": "4.8 (25 reviews)",
    "officialWebsite": null,
    "listingSource": "https://www.apartments.com/naya-sunnyvale-ca/prdh34v/",
    "closestCaltrain": "Sunnyvale",
    "distance": "2.0 mi",
    "walkTime": "not yet verified",
    "notes": "A second 2B/2B plan (Floor Plan E / Unit 302) was listed for Apr 12 and excluded from the eligible interpretation.",
    "researchDate": "2026-03-17",
    "primarySource": "Apartments.com live floor plan page"
  },
  {
    "apartment": "Redwood Place Apartment Homes",
    "city": "Sunnyvale",
    "address": "1030 Indian Wells Ave, Sunnyvale, CA 94085",
    "latitude": 37.3855813,
    "longitude": -122.0010644,
    "earliestAvailability": "2026-03-25",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "944-1,214",
    "listedRent": "$4,660-$6,425",
    "priceBasis": "Base rent",
    "floorplanUnit": "Plan 15 / Unit 124 Apr 9; Plan 40 / Unit 1131 Apr 5; Plan 48 / Unit 0960 Apr 9",
    "specials": null,
    "deposit": "Varies by floorplan",
    "leaseTerms": null,
    "review": "4.7 (4 reviews)",
    "officialWebsite": null,
    "listingSource": "https://www.apartments.com/redwood-place-apartment-homes-sunnyvale-ca/f5mc4nv/",
    "closestCaltrain": "Lawrence",
    "distance": "1.6 mi",
    "walkTime": "not yet verified",
    "notes": "Plan 15 / Unit 300 for Apr 24 was excluded from the eligible interpretation.",
    "researchDate": "2026-03-17",
    "primarySource": "Apartments.com live floor plan page"
  },
  {
    "apartment": "The Meadows Apartments",
    "city": "Sunnyvale",
    "address": "1000 Escalon Ave, Sunnyvale, CA 94085",
    "latitude": 37.38851,
    "longitude": -122.044975,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "915",
    "listedRent": "$4,100-$4,170",
    "priceBasis": "Base rent",
    "floorplanUnit": "B2 and B1 floorplans",
    "specials": null,
    "deposit": null,
    "leaseTerms": "Short-term lease available",
    "review": "4.8 (6 reviews)",
    "officialWebsite": "https://www.the-meadows.com",
    "listingSource": "https://www.apartments.com/the-meadows-apartments-sunnyvale-ca/4fzr7tk/",
    "closestCaltrain": "Sunnyvale",
    "distance": "1.4 mi",
    "walkTime": "not yet verified",
    "notes": "Both 2B/2B floorplans were listed as available now; utilities included in listing page include gas, water, heat, trash, sewer, and air conditioning.",
    "researchDate": "2026-03-17",
    "primarySource": "Apartments.com live floor plan page"
  },
  {
    "apartment": "Heritage Park",
    "city": "Sunnyvale",
    "address": "555 E Washington Ave, Sunnyvale, CA 94086",
    "latitude": 37.3744935,
    "longitude": -122.0221926,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "920",
    "listedRent": "$3,280-$4,460",
    "priceBasis": "Base rent",
    "floorplanUnit": "2x2 / Units 309E now, 1406E now, 1107W now, 409E Apr 8",
    "specials": null,
    "deposit": null,
    "leaseTerms": "1-12 months",
    "review": "4.5 (11 reviews)",
    "officialWebsite": "https://www.liveatheritageparkapts.com",
    "listingSource": "https://www.apartments.com/heritage-park-sunnyvale-ca/h2ctem3/",
    "closestCaltrain": "Sunnyvale",
    "distance": "0.7 mi",
    "walkTime": "13 min",
    "notes": "A 2x2 unit for Apr 12 was excluded from the eligible interpretation.",
    "researchDate": "2026-03-17",
    "primarySource": "Apartments.com live floor plan page"
  }
];
