const APARTMENTS = [
  {
    "apartment": "Stanford Villa",
    "city": "Palo Alto",
    "address": "3351-3375 Alma St, Palo Alto, CA 94306",
    "latitude": 37.4201642,
    "longitude": -122.1261222,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,000-1,050",
    "listedRent": "$3,650-$4,170",
    "priceBasis": "Base rent",
    "floorplanUnit": "Sequoia (Units 106 now, 140 Apr 1); Ponderosa (multiple units now)",
    "specials": null,
    "deposit": "$800",
    "leaseTerms": null,
    "review": "3.9 (5 reviews)",
    "officialWebsite": "https://www.stanfordvilla.com/apartments/ca/palo-alto/amenities",
    "listingSource": "https://www.apartments.com/stanford-villa-palo-alto-ca/5ezwzbq/",
    "closestCaltrain": "California Ave",
    "distance": "1.5 mi",
    "walkTime": "30 min",
    "notes": "Two 2B/2B floorplans were live: Sequoia 1,000 sq ft and Ponderosa 1,050 sq ft.",
    "researchDate": "2026-03-18",
    "primarySource": "Apartments.com live floor plan page",
    "walkTimeBasis": "Estimated from walking distance at 20 min/mile",
    "washer": "No in-unit washer/dryer",
    "washerNotes": "No in-unit laundry; official site lists on-site laundry facilities (card-operated), and Apartments.com says on-site laundry is shared resident use.",
    "sourceUrls": [
      "https://rde.stanford.edu/studenthousing/stanford-villa-apartments",
      "https://www.apartments.com/stanford-villa-palo-alto-ca/5ezwzbq/",
      "https://www.loopnet.com/property/3375-alma-st-palo-alto-ca-94306/06085-13228075/"
    ],
    "transitLaundryEvidence": "Official sources confirm on-site shared laundry rather than in-unit laundry. California Ave is the closest Caltrain stop; LoopNet showed 1.5 mi and Apartments.com showed 1.8 mi, so 1.5 mi was used.",
    "transitLaundryConfidence": 0.89
  },
  {
    "apartment": "Montage Apartments",
    "city": "Palo Alto",
    "address": "4020 El Camino Real, Palo Alto, CA 94306",
    "latitude": 37.4152258,
    "longitude": -122.1282764,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,000",
    "listedRent": "$4,995",
    "priceBasis": "Base rent",
    "floorplanUnit": "NEWLY REMODELED Upstairs 2BRx2BA",
    "specials": "One month free with a 15-month lease and immediate move-in",
    "deposit": "$1,000",
    "leaseTerms": "15 months for special",
    "review": "4.0 (0 reviews)",
    "officialWebsite": "https://montagebayarea.com/",
    "listingSource": "https://www.apartments.com/montage-apartments-palo-alto-ca/fqckbxs/",
    "closestCaltrain": "California Ave",
    "distance": "0.8 mi",
    "walkTime": "15 min",
    "notes": "Single 2B/2B floorplan listed as available now.",
    "researchDate": "2026-03-18",
    "primarySource": "Apartments.com live floor plan page",
    "walkTimeBasis": "Listed walking time/distance from third-party map result",
    "washer": "In-unit washer/dryer",
    "washerNotes": "Official site says in-home washer/dryers and washer/dryer in every home; Apartments.com also lists Washer/Dryer.",
    "sourceUrls": [
      "https://montagebayarea.com/",
      "https://www.apartments.com/montage-apartments-palo-alto-ca/fqckbxs/",
      "https://moovitapp.com/index/en/public_transit-El_Camino_Real_Palo_Alto_CA-SF_Bay_Area_CA-site_254528058-22",
      "https://www.loopnet.com/property/el-camino-real-palo-alto-ca-94306/06085-14220079/"
    ],
    "transitLaundryEvidence": "Official site and Apartments.com both confirm in-unit washer/dryer. California Ave is the nearest Caltrain stop; LoopNet listed it at 0.8 mi / 15 min walk.",
    "transitLaundryConfidence": 0.77
  },
  {
    "apartment": "Southwood Apartments",
    "city": "Palo Alto",
    "address": "2850 Middlefield Rd, Palo Alto, CA 94306",
    "latitude": 37.4320555,
    "longitude": -122.1273465,
    "earliestAvailability": "2026-04-10",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "980",
    "listedRent": "$4,195",
    "priceBasis": "Base rent",
    "floorplanUnit": "2x2A / Unit 113",
    "specials": null,
    "deposit": "$1,000",
    "leaseTerms": null,
    "review": "3.9 (1 review)",
    "officialWebsite": "https://www.southwood-apartments.com/",
    "listingSource": "https://www.apartments.com/southwood-apartments-palo-alto-ca/6f8zpmt/",
    "closestCaltrain": "California Ave",
    "distance": "1.3 mi",
    "walkTime": "26 min",
    "notes": "Only one 2B/2B unit was live and it becomes available on April 10, 2026.",
    "researchDate": "2026-03-18",
    "primarySource": "Apartments.com live floor plan page",
    "walkTimeBasis": "Estimated from walking distance at 20 min/mile using map/search distance",
    "washer": "In-unit washer/dryer",
    "washerNotes": "Official site says homes feature in-home washers and dryers, and Apartments.com also lists Washer/Dryer in apartment features.",
    "sourceUrls": [
      "https://www.southwood-apartments.com/",
      "https://www.southwood-apartments.com/floorplans/one-bedroom-one-bathroom",
      "https://www.apartments.com/southwood-apartments-palo-alto-ca/6f8zpmt/",
      "https://www.rome2rio.com/s/Palo-Alto/California-Ave-Caltrain-Station",
      "https://www.walkscore.com/score/middlefield-rd-and-colorado-ave-palo-alto-ca-94306"
    ],
    "transitLaundryEvidence": "Official site confirms in-home washer/dryer. Listing sites did not provide a walk route, so the California Ave walk time was estimated from map/search distance.",
    "transitLaundryConfidence": 0.74
  },
  {
    "apartment": "345 Sheridan Ave Unit SI FL3-ID806",
    "city": "Palo Alto",
    "address": "345 Sheridan Ave, Palo Alto, CA 94306",
    "latitude": 37.4250735,
    "longitude": -122.1407098,
    "earliestAvailability": "2026-03-18",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,097",
    "listedRent": "$4,090 lowest advertised; $4,400 for 1-year stay",
    "priceBasis": "Term-dependent furnished rate",
    "floorplanUnit": "Blueground unit SI FL3-ID806",
    "specials": null,
    "deposit": null,
    "leaseTerms": "1-12 months",
    "review": "n/a on unit listing",
    "officialWebsite": "https://www.theblueground.com/p/furnished-apartments/sfo-806?utm_campaign=SFO&utm_medium=Feed&utm_source=apartments",
    "listingSource": "https://www.apartments.com/345-sheridan-ave-palo-alto-ca-unit-si-fl3-id806/rhckc00/",
    "closestCaltrain": "California Ave",
    "distance": "0.4 mi",
    "walkTime": "8 min",
    "notes": "Furnished Blueground unit. Lowest rate depends on stay length; 1-year pricing was explicitly listed at $4,400/month.",
    "researchDate": "2026-03-18",
    "primarySource": "Apartments.com unit page",
    "walkTimeBasis": "Listed walk time on Apartments.com",
    "washer": "In-unit washer/dryer",
    "washerNotes": "Apartments.com says the apartment offers in-apartment laundry and lists Washer/Dryer in features.",
    "sourceUrls": [
      "https://www.apartments.com/345-sheridan-ave-palo-alto-ca-unit-si-fl3-id806/rhckc00/",
      "https://www.theblueground.com/m/furnished-apartments/palo-alto-ca-usa/f/bedrooms-2"
    ],
    "transitLaundryEvidence": "Apartments.com lists California Avenue Caltrain at 0.4 mi / 8 min walk and states the apartment has in-apartment laundry with washer/dryer.",
    "transitLaundryConfidence": 0.9
  },
  {
    "apartment": "Sevens",
    "city": "Mountain View",
    "address": "777 W Middlefield Rd, Mountain View, CA 94043",
    "latitude": 37.4027987,
    "longitude": -122.076013,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,021-1,240+",
    "listedRent": "$5,979-$7,184",
    "priceBasis": "Total monthly price",
    "floorplanUnit": "B4 (Units B-130 now, B-276 now, B-176 Mar 31, B-145 Mar 31); additional 2B/2B floorplans also listed",
    "specials": "Up to 8 weeks free base rent",
    "deposit": null,
    "leaseTerms": "Minimum lease term applies",
    "review": "5.0 (2 reviews)",
    "officialWebsite": "https://sevensmv.com/",
    "listingSource": "https://www.apartments.com/sevens-mountain-view-ca/3rr7vmg/",
    "closestCaltrain": "Mountain View",
    "distance": "~0.75 mi",
    "walkTime": "15 min",
    "notes": "At least one 2B/2B floorplan was available now and another set by Mar 31. Apartments.com labels pricing as total monthly price.",
    "researchDate": "2026-03-18",
    "primarySource": "Apartments.com live floor plan page",
    "walkTimeBasis": "Official site lists a 15-minute walk; distance back-calculated at 20 min/mile",
    "washer": "In-unit washer/dryer",
    "washerNotes": "Official amenities page lists In-Unit Washer and Dryer; Apartments.com and Zillow also list in-unit washer/dryer.",
    "sourceUrls": [
      "https://sevensmv.com/amenities/",
      "https://sevensmv.com/p/transportation/",
      "https://www.apartments.com/sevens-mountain-view-ca/3rr7vmg/",
      "https://www.zillow.com/apartments/mountain-view-ca/sevens/9VG5jp/"
    ],
    "transitLaundryEvidence": "Official site states Mountain View Caltrain Station is a 15-minute walk from Sevens and lists in-unit washer/dryer.",
    "transitLaundryConfidence": 0.91
  },
  {
    "apartment": "Rowe at Pear Village",
    "city": "Mountain View",
    "address": "1265 Pear Ave, Mountain View, CA 94043",
    "latitude": 37.4142233,
    "longitude": -122.0741342,
    "earliestAvailability": "2026-03-22",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,146-1,318",
    "listedRent": "$5,190-$5,650",
    "priceBasis": "Total monthly price",
    "floorplanUnit": "Unit 260 (1,146 sq ft, Mar 22); 2A.2 / Unit 332 (1,318 sq ft, Mar 25)",
    "specials": null,
    "deposit": null,
    "leaseTerms": null,
    "review": "4.9 (11 reviews)",
    "officialWebsite": "https://rowepearvillage.com/amenities/",
    "listingSource": "https://www.apartments.com/rowe-at-pear-village-mountain-view-ca/7fyfd6x/",
    "closestCaltrain": "Mountain View",
    "distance": "1.13 mi",
    "walkTime": "23 min",
    "notes": "A May 7 unit was excluded from the eligible interpretation because it misses the early-April cutoff.",
    "researchDate": "2026-03-18",
    "primarySource": "Apartments.com live floor plan page",
    "walkTimeBasis": "Estimated from the listed 1.13 mi distance at 20 min/mile",
    "washer": "In-unit washer/dryer",
    "washerNotes": "Official site says Whirlpool front-load washer and dryer in unit; Apartments.com and Zillow also list in-unit laundry.",
    "sourceUrls": [
      "https://rowepearvillage.com/amenities/",
      "https://www.apartments.com/rowe-at-pear-village-mountain-view-ca/7fyfd6x/",
      "https://www.apartmenthomeliving.com/apartment-finder/Rowe-at-Pear-Village-Mountain-View-CA-94043-19859551",
      "https://www.caltrain.com/station/mountainview"
    ],
    "transitLaundryEvidence": "Official amenities page lists in-unit washer/dryer. ApartmentHomeLiving lists Mountain View Caltrain at 1.13 mi; no direct walking route was exposed, so time was estimated.",
    "transitLaundryConfidence": 0.79
  },
  {
    "apartment": "Landsby",
    "city": "Mountain View",
    "address": "2580-2590 California St, Mountain View, CA 94040",
    "latitude": 37.4052864,
    "longitude": -122.109234,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "964-1,047",
    "listedRent": "$5,618-$5,710",
    "priceBasis": "Total monthly price",
    "floorplanUnit": "2A-6 / Unit 1511 now; 2K-1 / Unit 3521 Mar 21; 2B-1 / Unit 3319 Mar 23",
    "specials": null,
    "deposit": null,
    "leaseTerms": null,
    "review": "4.6 (57 reviews)",
    "officialWebsite": "https://livelandsby.com/",
    "listingSource": "https://www.apartments.com/landsby-mountain-view-ca/8mzlqg0/",
    "closestCaltrain": "San Antonio",
    "distance": "0.2 mi",
    "walkTime": "4 min",
    "notes": "A second 2B-1 unit for May 8 was excluded from the eligible interpretation.",
    "researchDate": "2026-03-18",
    "primarySource": "Apartments.com live floor plan page",
    "walkTimeBasis": "Listing-provided walking time",
    "washer": "In-unit washer/dryer",
    "washerNotes": "Apartments.com says Landsby has in-unit washers/dryers; official amenities page lists a GE front-load washer & dryer in select homes.",
    "sourceUrls": [
      "https://livelandsby.com/",
      "https://livelandsby.com/amenities/",
      "https://www.apartments.com/landsby-mountain-view-ca/8mzlqg0/"
    ],
    "transitLaundryEvidence": "Official site says Landsby is a short walk to San Antonio Caltrain; Apartments.com lists San Antonio at 0.2 mi / 4 min walk and confirms in-unit laundry.",
    "transitLaundryConfidence": 0.97
  },
  {
    "apartment": "Verve",
    "city": "Mountain View",
    "address": "2020 W El Camino Real, Mountain View, CA 94040",
    "latitude": 37.3947662,
    "longitude": -122.1000645,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,121-1,651",
    "listedRent": "$5,139-$5,736",
    "priceBasis": "Base rent",
    "floorplanUnit": "B2A / Unit 322 now; B2G / Unit 410 Mar 27",
    "specials": null,
    "deposit": null,
    "leaseTerms": null,
    "review": "4.0 (0 reviews)",
    "officialWebsite": "https://www.udr.com/san-francisco-bay-area-apartments/mountain-view/verve/amenities/",
    "listingSource": "https://www.apartments.com/verve-mountain-view-ca/dfw92yk/",
    "closestCaltrain": "San Antonio",
    "distance": "0.66 mi",
    "walkTime": "13 min",
    "notes": "Another 2B/2B unit (B2J / Unit 412) was listed for Apr 23 and excluded from the eligible interpretation.",
    "researchDate": "2026-03-18",
    "primarySource": "Apartments.com live floor plan page",
    "walkTimeBasis": "Estimated from listed distance at 20 min/mile because no explicit walking time was published",
    "washer": "In-unit washer/dryer",
    "washerNotes": "Official UDR amenities page says in-home washer/dryer; Apartments.com and ApartmentHomeLiving also list in-unit Washer/Dryer.",
    "sourceUrls": [
      "https://www.udr.com/san-francisco-bay-area-apartments/mountain-view/verve/neighborhood/",
      "https://www.apartments.com/verve-mountain-view-ca/dfw92yk/",
      "https://www.apartmenthomeliving.com/apartment-finder/Verve-Mountain-View-CA-94040-3051240",
      "https://www.caltrain.com/station/sanantonio"
    ],
    "transitLaundryEvidence": "Official UDR pages say Verve has an in-home washer/dryer. ApartmentHomeLiving lists San Antonio Caltrain as the closest stop at 0.66 mi.",
    "transitLaundryConfidence": 0.79
  },
  {
    "apartment": "The Shadows Apartments",
    "city": "Mountain View",
    "address": "750 N Shoreline Blvd, Mountain View, CA 94043",
    "latitude": 37.4050688,
    "longitude": -122.0782316,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,025",
    "listedRent": "$4,595",
    "priceBasis": "Base rent",
    "floorplanUnit": "E floorplan",
    "specials": "$1,000 off when you look and lease; water, sewer, and garbage included in rent",
    "deposit": "$800",
    "leaseTerms": null,
    "review": "4.0 (0 reviews)",
    "officialWebsite": "https://www.shadowsapartments.com/",
    "listingSource": "https://www.apartments.com/the-shadows-apartments-mountain-view-ca/ysm3jjr/",
    "closestCaltrain": "Mountain View",
    "distance": "1.0 mi",
    "walkTime": "18 min",
    "notes": "The 2B/2B floorplan was listed as available now without individual unit rows on Apartments.com.",
    "researchDate": "2026-03-18",
    "primarySource": "Apartments.com live floor plan page",
    "walkTimeBasis": "Reported walking time from property transit listing",
    "washer": "In-unit washer/dryer",
    "washerNotes": "Official site and Apartments.com both list in-unit washer/dryer; Apartments.com also lists shared laundry facilities in the community.",
    "sourceUrls": [
      "https://www.shadowsapartments.com/",
      "https://www.apartments.com/the-shadows-apartments-mountain-view-ca/ysm3jjr/",
      "https://www.loopnet.com/property/750-n-shoreline-blvd-mountain-view-ca-94043/06085-15031038/",
      "https://www.caltrain.com/station/mountainview"
    ],
    "transitLaundryEvidence": "Official site and Apartments.com identify The Shadows at 750 N Shoreline Blvd and both list in-unit washer/dryer. LoopNet shows Mountain View Caltrain at 1.0 mi / 18 min walk.",
    "transitLaundryConfidence": 0.87
  },
  {
    "apartment": "MV Apartments",
    "city": "Mountain View",
    "address": "2700 W El Camino Real, Mountain View, CA 94040",
    "latitude": 37.3857514,
    "longitude": -122.0841169,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,013",
    "listedRent": "$5,549",
    "priceBasis": "Base rent",
    "floorplanUnit": "Chestnut / Unit 528 now",
    "specials": null,
    "deposit": null,
    "leaseTerms": null,
    "review": "4.8 (13 reviews)",
    "officialWebsite": "https://www.mvapartments.com/",
    "listingSource": "https://www.apartments.com/mv-apartments-mountain-view-ca/tlm9sdb/",
    "closestCaltrain": "San Antonio",
    "distance": "0.9 mi",
    "walkTime": "16 min",
    "notes": "A second Chestnut unit for Apr 14 was excluded from the eligible interpretation because it is after the cutoff.",
    "researchDate": "2026-03-18",
    "primarySource": "Apartments.com live floor plan page",
    "walkTimeBasis": "Listing-stated walking time on Apartments.com",
    "washer": "In-unit washer/dryer",
    "washerNotes": "Official site lists in-home laundry appliances and a full-size front-loading washer and dryer; Apartments.com also lists in-unit washers and dryers.",
    "sourceUrls": [
      "https://www.mvapartments.com/",
      "https://www.apartments.com/mv-apartments-mountain-view-ca/tlm9sdb/"
    ],
    "transitLaundryEvidence": "Official MV Apartments site advertises in-home laundry appliances/full-size front-loading washer and dryer. Apartments.com lists San Antonio at 0.9 mi / 16 min walk.",
    "transitLaundryConfidence": 0.96
  },
  {
    "apartment": "Maplewood Apartments",
    "city": "Mountain View",
    "address": "1885 California St, Mountain View, CA 94043",
    "latitude": 37.3960388,
    "longitude": -122.0942791,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "947",
    "listedRent": "$3,700-$3,800",
    "priceBasis": "Base rent",
    "floorplanUnit": "Plan B1 / Unit 29 now; Unit 31 Apr 7",
    "specials": "Up to 1 month on us",
    "deposit": "$600",
    "leaseTerms": null,
    "review": "4.0 (0 reviews)",
    "officialWebsite": "https://livemaplewoodca.com/amenities.aspx",
    "listingSource": "https://www.apartments.com/maplewood-apartments-mountain-view-ca/0h511d1/",
    "closestCaltrain": "Mountain View",
    "distance": "1.3 mi",
    "walkTime": "26 min",
    "notes": "Two 2B/2B units were live and both meet the early-April cutoff.",
    "researchDate": "2026-03-18",
    "primarySource": "Apartments.com live floor plan page",
    "walkTimeBasis": "Estimated from the listed 1.3 mi distance at 20 min/mile; no published walking route was found",
    "washer": "In-unit washer/dryer",
    "washerNotes": "Official site lists In-Home Washer & Dryer; Apartments.com also says units have in-unit washers and dryers.",
    "sourceUrls": [
      "https://livemaplewoodca.com/amenities.aspx",
      "https://www.apartments.com/maplewood-apartments-mountain-view-ca/0h511d1/",
      "https://www.apartmentfinder.com/California/Mountain-View-Apartments/Maplewood-Apartments"
    ],
    "transitLaundryEvidence": "Official Maplewood site shows 1885 California St and in-home washer/dryer. Apartments.com lists Mountain View Caltrain at 1.3 mi and San Antonio at 1.5 mi.",
    "transitLaundryConfidence": 0.68
  },
  {
    "apartment": "Hartwood",
    "city": "Sunnyvale",
    "address": "401 Willow Ave, Sunnyvale, CA 94086",
    "latitude": 37.3699627,
    "longitude": -121.9976623,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,223",
    "listedRent": "$5,200-$5,515",
    "priceBasis": "Base rent",
    "floorplanUnit": "2 Bed/2 Bath-B5 / Unit 2109 now; Unit 2402 Apr 5; Unit 1307 Apr 7",
    "specials": "Exceptional leasing specials available for a limited time",
    "deposit": null,
    "leaseTerms": null,
    "review": "4.0 (0 reviews)",
    "officialWebsite": "https://www.hartwoodsunnyvale.com/",
    "listingSource": "https://www.apartments.com/hartwood-sunnyvale-ca/nzqhytq/",
    "closestCaltrain": "Lawrence",
    "distance": "0.1 mi",
    "walkTime": "1 min",
    "notes": "Other 2B/2B floorplans were listed but marked not available; B5 is the live qualifying option.",
    "researchDate": "2026-03-18",
    "primarySource": "Apartments.com live floor plan page",
    "walkTimeBasis": "Listed walking time from Apartments.com",
    "washer": "In-unit washer/dryer",
    "washerNotes": "Apartments.com lists Washer/Dryer in apartment features and says Hartwood has units with in-unit washers and dryers; the official site does not mention laundry.",
    "sourceUrls": [
      "https://www.hartwoodsunnyvale.com/neighborhood/",
      "https://www.apartments.com/hartwood-sunnyvale-ca/nzqhytq/"
    ],
    "transitLaundryEvidence": "Hartwood\u2019s official site says it is steps from Lawrence Station. Apartments.com lists Lawrence Caltrain at 0.1 mi / 1 min walk and confirms in-unit washer/dryer.",
    "transitLaundryConfidence": 0.88
  },
  {
    "apartment": "Savoy",
    "city": "Sunnyvale",
    "address": "1120 Kifer Rd, Sunnyvale, CA",
    "latitude": 37.3732914,
    "longitude": -121.9998913,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,228-1,344",
    "listedRent": "$4,946-$5,108",
    "priceBasis": "Total monthly price",
    "floorplanUnit": "B5.4 / Unit 1-415 now; B5 / Unit 2-550 Mar 24; B7 / Unit 2-321 Apr 8",
    "specials": null,
    "deposit": "$600",
    "leaseTerms": null,
    "review": "4.4 (98 reviews)",
    "officialWebsite": "https://liveatsavoy.com/",
    "listingSource": "https://www.apartments.com/savoy-sunnyvale-ca/wz9c7ck/",
    "closestCaltrain": "Lawrence",
    "distance": "0.6 mi",
    "walkTime": "12 min",
    "notes": "A B5 unit for Apr 23 and a B2 unit for Apr 29 were excluded from the eligible interpretation.",
    "researchDate": "2026-03-18",
    "primarySource": "Apartments.com live floor plan page",
    "walkTimeBasis": "Listed walking time on Apartments.com",
    "washer": "In-unit washer/dryer",
    "washerNotes": "Apartments.com lists Washer/Dryer under apartment features. The official site does not explicitly mention laundry, but nothing suggests shared-only laundry.",
    "sourceUrls": [
      "https://liveatsavoy.com/",
      "https://liveatsavoy.com/amenities/",
      "https://www.apartments.com/savoy-sunnyvale-ca/wz9c7ck/"
    ],
    "transitLaundryEvidence": "Official site says Savoy is made accessible by Lawrence Station Caltrain and lists the property at 1120 Kifer Road. Apartments.com lists Lawrence at 0.6 mi / 12 min walk and shows washer/dryer in apartment features.",
    "transitLaundryConfidence": 0.88
  },
  {
    "apartment": "Encasa",
    "city": "Sunnyvale",
    "address": "550 E Weddell Dr, Sunnyvale, CA 94089",
    "latitude": 37.3988598,
    "longitude": -122.0142129,
    "earliestAvailability": "2026-03-24",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,175",
    "listedRent": "$4,855",
    "priceBasis": "Total monthly price",
    "floorplanUnit": "2x2e / Unit 7423",
    "specials": null,
    "deposit": null,
    "leaseTerms": null,
    "review": "4.2 (24 reviews)",
    "officialWebsite": "https://www.encasaliving.com/Contact.aspx",
    "listingSource": "https://www.apartments.com/encasa-sunnyvale-ca/s1ktnb6/",
    "closestCaltrain": "Lawrence",
    "distance": "3.0 mi",
    "walkTime": "60 min",
    "notes": "Only one live 2B/2B unit met the cutoff; the rest of the 2B/2B plans were not available.",
    "researchDate": "2026-03-18",
    "primarySource": "Apartments.com live floor plan page",
    "walkTimeBasis": "Estimated from listed walking distance at 20 min/mile",
    "washer": "In-unit washer/dryer",
    "washerNotes": "Official site lists In Unit Washer & Dryer - Stackable; Apartments.com also lists in-unit washer/dryer.",
    "sourceUrls": [
      "https://www.encasaliving.com/Contact.aspx",
      "https://www.apartments.com/es/encasa-sunnyvale-ca/s1ktnb6/"
    ],
    "transitLaundryEvidence": "Encasa\u2019s official site lists an in-unit stackable washer/dryer. Apartments.com shows Lawrence as the closest Caltrain stop at 3.0 mi, so the walk time was estimated.",
    "transitLaundryConfidence": 0.84
  },
  {
    "apartment": "Naya",
    "city": "Sunnyvale",
    "address": "1095 W El Camino Real, Sunnyvale, CA 94087",
    "latitude": 37.3734276,
    "longitude": -122.0512255,
    "earliestAvailability": "2026-03-19",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "1,013",
    "listedRent": "$4,789",
    "priceBasis": "Total monthly price",
    "floorplanUnit": "Floor Plan C / Unit 303",
    "specials": null,
    "deposit": null,
    "leaseTerms": null,
    "review": "4.8 (25 reviews)",
    "officialWebsite": "https://www.greystar.com/naya-sunnyvale-ca/p_17093",
    "listingSource": "https://www.apartments.com/naya-sunnyvale-ca/prdh34v/",
    "closestCaltrain": "Sunnyvale",
    "distance": "1.2 mi",
    "walkTime": "24 min",
    "notes": "A second 2B/2B plan (Floor Plan E / Unit 302) was listed for Apr 12 and excluded from the eligible interpretation.",
    "researchDate": "2026-03-18",
    "primarySource": "Apartments.com live floor plan page",
    "walkTimeBasis": "Estimated from Walk Score rail-line distance at 20 min/mile; no explicit walking time was found on listing sites",
    "washer": "Likely in-unit washer/dryer (conflicting sources)",
    "washerNotes": "Greystar\u2019s official page lists Washer/Dryer and Full Size Washer/Dryer, but Apartments.com FAQ contradicts that with a no in-unit/shared-laundry statement. Official site indicates in-unit laundry; third-party listing is inconsistent.",
    "sourceUrls": [
      "https://www.greystar.com/naya-sunnyvale-ca/p_17093",
      "https://www.apartments.com/naya-sunnyvale-ca/prdh34v/",
      "https://www.walkscore.com/score/naya-two-br-sunnyvale"
    ],
    "transitLaundryEvidence": "Official Naya listing places the property at 1095 W El Camino Real and shows washer/dryer. Walk Score for that address shows rail lines 1.2 mi away, which was used as the best walk-distance proxy.",
    "transitLaundryConfidence": 0.69
  },
  {
    "apartment": "Redwood Place Apartment Homes",
    "city": "Sunnyvale",
    "address": "1030 Indian Wells Ave, Sunnyvale, CA 94085",
    "latitude": 37.3855813,
    "longitude": -122.0010644,
    "earliestAvailability": "2026-03-25",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "944-1,214",
    "listedRent": "$4,660-$6,425",
    "priceBasis": "Base rent",
    "floorplanUnit": "Plan 15 / Unit 124 Apr 9; Plan 40 / Unit 1131 Apr 5; Plan 48 / Unit 0960 Apr 9",
    "specials": null,
    "deposit": "Varies by floorplan",
    "leaseTerms": null,
    "review": "4.7 (4 reviews)",
    "officialWebsite": "https://www.irvinecompanyapartments.com/locations/northern-california/sunnyvale/redwood-place.html",
    "listingSource": "https://www.apartments.com/redwood-place-apartment-homes-sunnyvale-ca/f5mc4nv/",
    "closestCaltrain": "Lawrence",
    "distance": "1.33 mi",
    "walkTime": "28 min",
    "notes": "Plan 15 / Unit 300 for Apr 24 was excluded from the eligible interpretation.",
    "researchDate": "2026-03-18",
    "primarySource": "Apartments.com live floor plan page",
    "walkTimeBasis": "Direct walking result from Moovit for the same address, not an estimate",
    "washer": "In-unit washer/dryer",
    "washerNotes": "Official site lists in-home washer & dryer; Apartments.com also lists Washer/Dryer.",
    "sourceUrls": [
      "https://www.irvinecompanyapartments.com/locations/northern-california/sunnyvale/redwood-place.html",
      "https://www.irvinecompanyapartments.com/locations/northern-california/sunnyvale/redwood-place/features.html",
      "https://www.apartments.com/redwood-place-apartment-homes-sunnyvale-ca/f5mc4nv/",
      "https://moovitapp.com/index/en/public_transit-Santa_Clara_Square-SF_Bay_Area_CA-site_268971200-22"
    ],
    "transitLaundryEvidence": "Official Irvine Company pages confirm the address and in-home washer/dryer. Moovit lists Lawrence as the nearest train station at about 1.33 mi / 28 min walk.",
    "transitLaundryConfidence": 0.89
  },
  {
    "apartment": "The Meadows Apartments",
    "city": "Sunnyvale",
    "address": "1000 Escalon Ave, Sunnyvale, CA 94085",
    "latitude": 37.38851,
    "longitude": -122.044975,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "915",
    "listedRent": "$4,100-$4,170",
    "priceBasis": "Base rent",
    "floorplanUnit": "B2 and B1 floorplans",
    "specials": null,
    "deposit": null,
    "leaseTerms": "Short-term lease available",
    "review": "4.8 (6 reviews)",
    "officialWebsite": "https://www.the-meadows.com/",
    "listingSource": "https://www.apartments.com/the-meadows-apartments-sunnyvale-ca/4fzr7tk/",
    "closestCaltrain": "Sunnyvale",
    "distance": "1.5 mi",
    "walkTime": "30 min",
    "notes": "Both 2B/2B floorplans were listed as available now; utilities included in listing page include gas, water, heat, trash, sewer, and air conditioning.",
    "researchDate": "2026-03-18",
    "primarySource": "Apartments.com live floor plan page",
    "walkTimeBasis": "Estimated at 20 min/mile from the best available distance; no source exposed an explicit walking route",
    "washer": "In-unit washer/dryer",
    "washerNotes": "Official amenities page lists Washer & Dryer Included; Apartments.com also shows in-unit washer/dryer.",
    "sourceUrls": [
      "https://www.the-meadows.com/apartments/ca/sunnyvale/amenities",
      "https://www.the-meadows.com/",
      "https://www.apartments.com/the-meadows-apartments-sunnyvale-ca/4fzr7tk/",
      "https://www.apartments.com/1000-escalon-ave-sunnyvale-ca-unit-id1257646p/lj5swqg/",
      "https://www.mapquest.com/us/california/caltrain-station-sunnyvale-305999636",
      "https://www.caltrain.com/destinations/sunnyvale"
    ],
    "transitLaundryEvidence": "Official site says the property is a short walk to Caltrain and explicitly lists Washer & Dryer Included. Because no walking route was exposed on listing pages, the walk time is estimated.",
    "transitLaundryConfidence": 0.76
  },
  {
    "apartment": "Heritage Park",
    "city": "Sunnyvale",
    "address": "555 E Washington Ave, Sunnyvale, CA 94086",
    "latitude": 37.3744935,
    "longitude": -122.0221926,
    "earliestAvailability": "Now",
    "availableBy": "2026-04-10",
    "beds": "2",
    "baths": "2",
    "sqFt": "920",
    "listedRent": "$3,280-$4,460",
    "priceBasis": "Base rent",
    "floorplanUnit": "2x2 / Units 309E now, 1406E now, 1107W now, 409E Apr 8",
    "specials": null,
    "deposit": null,
    "leaseTerms": "1-12 months",
    "review": "4.5 (11 reviews)",
    "officialWebsite": "https://www.liveatheritageparkapts.com/amenities",
    "listingSource": "https://www.apartments.com/heritage-park-sunnyvale-ca/h2ctem3/",
    "closestCaltrain": "Sunnyvale",
    "distance": "0.7 mi",
    "walkTime": "13 min",
    "notes": "A 2x2 unit for Apr 12 was excluded from the eligible interpretation.",
    "researchDate": "2026-03-18",
    "primarySource": "Apartments.com live floor plan page",
    "walkTimeBasis": "Listed walking time/distance from Apartments.com commuter rail listing",
    "washer": "No in-unit washer/dryer",
    "washerNotes": "Official amenities list Laundry Facilities as a community amenity, and Apartments.com FAQ says Heritage Park does not provide in-unit laundry and has on-site laundry facilities for shared resident use.",
    "sourceUrls": [
      "https://www.liveatheritageparkapts.com/amenities",
      "https://www.apartments.com/heritage-park-sunnyvale-ca/h2ctem3/"
    ],
    "transitLaundryEvidence": "Official site confirms proximity to Sunnyvale Caltrain and lists community laundry facilities. Apartments.com specifies a 13-minute, 0.7-mile walk and states there is no in-unit laundry.",
    "transitLaundryConfidence": 0.95
  }
];
